### PR TITLE
Use Terraform Cloud for Terraform remote state management

### PR DESCRIPTION
**Pull request by cdepillabout**
This PR sets up Terraform to use [Terraform Cloud](https://app.terraform.io) for remote state management.

Here's some documentation on Terraform Cloud that was a little helpful when I was trying to figure out how it works:
- https://www.terraform.io/cloud-docs
- https://learn.hashicorp.com/collections/terraform/cloud-get-started

### CODE REVIEW

**Comment by cdepillabout** [comment]
With this PR, we're now using Terraform Cloud for remote state management.  That means that if one person does `terraform apply`, then someone else should be able to run `terraform plan` and see that no changes need to be made to the output.  Everyone should also be able to run `terraform output` to get the server IP address.

@kayhide @jonascarpay I just did a `terraform apply`.  Would one of you be able to run a `terraform plan` or `terraform apply` from this PR and confirm that Terraform says that no changes need to be made?  (Terraform might actually want to replace the EC2 instance, depending on the logic for creating/hashing the AMI image, but Terraform definitely shouldn't want to replace resources like the `aws_iam_policy` and `aws_s3_bucket`.)

You will probably have to run through the steps in the README.md I've added in this PR in order to login to Terraform Cloud.

**Review by kayhide — APPROVED** [review]
Thanks for your setting up the terraform infra!
And nice documentation!

I followed the documentation and confirmed `terraform plan` to say nothing to change.
And I also successfully downloaded `vim` from the deployed server.
It is working really nicely!

**Comment by cdepillabout** [comment]
@jonascarpay If you wanted to test this as well, feel free to run `terraform destroy` when you're done.  We don't necessarily need to leave everything running if we're not using it!

**Review by jonascarpay — APPROVED** [review]
Thanks, this all seems to work great. The only nit is that I think a better place for the documentation is in `deploy/README.md`

**Comment by cdepillabout** [comment]
I rebased this on `master` and moved the deployment instructions from `README.md` to `deploy/README.md`.

**Pull request merged**
